### ISSUE TITLE
How to configure database

### ISSUE THREAD

**Issue by StarkTemplar** [ZionDials/Go-CDR#46]
Can you describe how the database should be configured for this to function? In my case I am using MS SQL.

- Does a specific table need created? Or is this the function of the autoMigrate setting that will create the necessary table(s)?
- What permissions does this user need? sysadmin? Can this be reduced to read/write once the tables have been created?
- Should the autoMigrate setting be disabled after the first time this is run?

**Comment by ZionDials** [comment]
Working with privately to resolve this. There appears to be an issue with the configuration file being provided to Go-CDR.
